[package]
name = "vibetorio-sim"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
bevy_ecs.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
